# This file is part of espzero, automatically synced from
# https://github.com/roboticsware/espzero at revision 24cae2bc1c028458052675181e95f2a08fdf7481.
# Do not edit this file directly — run update_user_libs.py espzero instead.

"""
espzero/__init__.py
Public entry point for the espzero library — an ESP32 port of picozero.

Quick start — picozero style (no explicit begin() needed)::

    from espzero import esp_led       # board is auto-detected on import
    from time import sleep

    while True:
        esp_led.on()
        sleep(1)
        esp_led.off()
        sleep(1)

Or specify a board explicitly before using any other class::

    import espzero
    espzero.begin("esp32_devkit_v1")  # override auto-detection

    from espzero import LED, Button, Servo, WiFi

The board profile system abstracts hardware differences (pin aliases,
ADC attenuation, strapping pins, NeoPixel vs GPIO LEDs, etc.) so that
user code remains identical across supported boards.
"""

import _hal

# ── Board → profile class mapping ─────────────────────────────
# Key   : user-facing board name (passed to begin())
# Value : (module_name, class_name) for lazy import
_PROFILE_MAP = {
    "esp32_devkit_v1":    ("profiles.esp32_boards", "ESP32DevKitV1"),
    "esp32_s3_devkit":    ("profiles.esp32_boards", "ESP32S3DevKit"),
    "esp32_c3_mini":      ("profiles.esp32_boards", "ESP32C3Mini"),
    "m5stack_atom":       ("profiles.esp32_boards", "M5StackAtom"),
    "wemos_d1_mini32":    ("profiles.esp32_boards", "WemosD1Mini32"),
    "esp8266_lolin_v3":   ("profiles.esp32_boards", "ESP8266LolinV3"),
    "esp32_38pin_nodemcu":("profiles.esp32_boards", "ESP32_38Pin_NodeMCU"),
}

# ── esp_led: lazy proxy for the built-in LED ──────────────────
# Behaves exactly like a DigitalLED / NeoPixelLED but auto-calls begin()
# on first use so that 'from espzero import esp_led' works without an
# explicit begin() call — same pattern as picozero's pico_led.

class _LazyLED:
    """
    Transparent proxy for the board's built-in LED.

    On the first method call or attribute access, auto-detects the board
    (begin('auto')) if begin() has not already been called.  After that,
    every call is forwarded to the real LED object created by begin().

    Calling begin('specific_board') before accessing esp_led is also
    supported — the proxy picks up the LED set by that call.
    """

    def _real(self):
        """Return the actual LED object, initialising if necessary."""
        global _esp_led_obj
        if _esp_led_obj is None:
            begin()           # auto-detect board and create the real LED
        return _esp_led_obj

    # ── Core LED API ───────────────────────────────────────────────
    def on(self, *a, **kw):    return self._real().on(*a, **kw)
    def off(self):             return self._real().off()
    def toggle(self):          return self._real().toggle()
    def blink(self, *a, **kw): return self._real().blink(*a, **kw)
    def pulse(self, *a, **kw): return self._real().pulse(*a, **kw)
    def close(self):           return self._real().close()

    @property
    def value(self):           return self._real().value
    @value.setter
    def value(self, v):        self._real().value = v

    @property
    def is_active(self):       return self._real().is_active
    @property
    def is_lit(self):          return self._real().is_active

    def __str__(self):
        return str(self._real())


_esp_led_obj    = None   # backing LED object; set by begin()
esp_led         = _LazyLED()  # always-valid proxy — import safely at any time
esp_temp_sensor = None   # Built-in temperature sensor (ESPTemperatureSensor)


def begin(board="auto"):
    """
    Initialise the board profile.  Must be called before any espzero class.

    :param board:
        - ``"auto"``          – detect from ``sys.implementation._machine``
        - A board name string – e.g. ``"esp32_devkit_v1"``
        - A ``BoardProfile`` instance – for custom boards

    Raises ``ValueError`` for unknown board name strings.
    """
    global _esp_led_obj, esp_temp_sensor

    from profiles._base import BoardProfile

    if isinstance(board, BoardProfile):
        _hal._profile = board

    elif board == "auto":
        from profiles.auto import detect
        begin(detect())
        return

    else:
        if board not in _PROFILE_MAP:
            raise ValueError(
                "[espzero] Unknown board: '{}'. "
                "Available boards: {}".format(board, list(_PROFILE_MAP.keys()))
            )
        mod_name, cls_name = _PROFILE_MAP[board]
        import importlib
        mod = importlib.import_module(mod_name)
        _hal._profile = getattr(mod, cls_name)()

    print("[espzero] Board: {} ({})".format(
        _hal._profile.NAME, _hal._profile.CHIP))

    # Initialise built-in LED — branch on LED type declared in the profile.
    # Stores the real object in _esp_led_obj; esp_led proxy picks it up automatically.
    from _core import NeoPixelLED, LED as _LED
    try:
        p = _hal._profile
        if p.INTERNAL_LED_TYPE == "neopixel":
            _esp_led_obj = NeoPixelLED(p.resolve_pin("internal"))
        else:
            _esp_led_obj = _LED("internal",
                                pwm=False,
                                active_high=p.INTERNAL_LED_ACTIVE_HIGH)
    except Exception:
        _esp_led_obj = None

    # Initialise built-in temperature sensor
    from _core import ESPTemperatureSensor
    esp_temp_sensor = ESPTemperatureSensor()


# ── Re-export public API ───────────────────────────────────────
from _core import (
    LED, DigitalLED, PWMLED, NeoPixelLED,
    Buzzer, PWMBuzzer, Speaker,
    RGBLED,
    Servo,
    Motor, Robot, Rover, Stepper,
    Button, Switch, MotionSensor, TouchSensor,
    Potentiometer, Pot,
    TemperatureSensor, TempSensor, Thermistor,
    DistanceSensor,
    ESPTemperatureSensor,
    DigitalOutputDevice, PWMOutputDevice,
    DigitalInputDevice, AnalogInputDevice,
)
from _wifi  import WiFi
from _touch import CapTouch
